### ISSUE TITLE
wrong column name - plan_MD5

### ISSUE THREAD

**Issue by sql-aus-hh** [OpenQueryStore/OpenQueryStore#10]
Hi there,

I tried to install OQS on a SQL Server 2008R2 (10.50.6220.0) EE on Windows Server 2008R2 Std + SP1 (both English).

I got error message that columns doesn't exist 
In Create Procedure "Gather_statistics" the column name was written "plan_md5" and "my" SQL Server doesn't know that columns... I tried with "plan_MD5" (that's the column name) everything worked.

BR Bjoern

**Comment by Evdlaar** [comment]
Hi Bjoern,

Thanks for creating the issue!
This is a collation issue that can occur, we are working on a fix that will avoid these issues in the future releases.

Thanks!

Enrico

**Comment by Evdlaar** [comment]
I just commited a new version that correctly sets the columnnames to including uppercase MD5.
