### ISSUE TITLE
no lines inserted because of truncation 

### ISSUE THREAD

**Issue by sql-aus-hh** [OpenQueryStore/OpenQueryStore#11]
Hi there,

I tried to install OQS on a SQL Server 2008R2 (10.50.6220.0) EE on Windows Server 2008R2 Std + SP1 (both English).

Next issue :
process / gathering is running
Log-table shows following entries:
Log_LogID	Log_LogRunID	Log_DateTime	Log_Message
1	1	2017-06-13 08:47:52.310	OpenQueryStore capture script started...
2	1	2017-06-13 08:47:52.390	OpenQueryStore captured 0 new plan(s)...
3	1	2017-06-13 08:47:52.393	OpenQueryStore captured 0 new queries...
4	1	2017-06-13 08:47:52.450	OpenQueryStore captured 0 runtime statistics...
5	1	2017-06-13 08:47:52.460	OpenQueryStore capture script finished...

In SQL Server Log I'm seeing following
The activated proc '[oqs].[ActivateOQSScheduler]' running on queue 'plmtst.dbo.OQSScheduler' output the following:  'The user does not have permission to perform this action.' (Might be another issue ?!)

Then I tried to execute "  EXEC [oqs].[Gather_Statistics] @logmode=1"
and received 
"_Msg 8152, Level 16, State 10, Procedure Gather_Statistics, Line 38 
String or binary data would be truncated._"

Line 38 contains of the cte with INSERT INTO [oqs].[Plans] ...

executing the cte separatly also ends in 
_Msg 8152, Level 16, State 10, Line 1
String or binary data would be truncated.
The statement has been terminated._

I try to figure out some more details on this... if needed...

BR Bjoern

**Comment by sql-aus-hh** [comment]
It is coming from the first column

CONVERT(varbinary, SUBSTRING(sys.fn_sqlvarbasetostr(HASHBYTES('MD5',  CONVERT(nvarchar(max),n.query('.')))),3,32))

it is defined as "int, not null" and if I replace the converts with a "0" everything is fine.
But I can't test it any further, there is no resultset for the pure select

**Comment by Evdlaar** [comment]
Hi Bjoern,

I just uploaded a new version that correctly sets the columnnames to including uppercase MD5.
This might also have effect on this specific query, can you test that?

I just ran the code on my machine and it works, but it is not a 2008R2 Instance.
We will run a test on 2008R2.

Thanks!

**Comment by sql-williamd** [comment]
It was down to hashbytes having an 8000 char/byte limit. The issue was a little tricky, but Enrico managed to fix it.

You can extract the sproc definition from the installer and it will work fine.

An uninstall/update script is something for our to-do list :)

**Comment by sql-aus-hh** [comment]
Ran without any error... also with activated scheduler... it looks ok now BUT another question because there is a "new" logentry in sql server log:

The activated proc '[oqs].[ActivateOQSScheduler]' running on queue 'xyz.dbo.OQSScheduler' output the following:  'The user does not have permission to perform this action.'

I'm connected to the server as a sysadmin and as that I ran installer script... who should have more rights/permissions?

**Comment by sql-aus-hh** [comment]
and in Log-table I found the following (looping):

Log_LogID	Log_LogRunID	Log_DateTime	Log_Message
1321	265	2017-06-14 16:09:07.183	OpenQueryStore capture script started...
1322	265	2017-06-14 16:09:07.190	OpenQueryStore captured 0 new plan(s)...
1323	265	2017-06-14 16:09:07.190	OpenQueryStore captured 0 new queries...
1324	265	2017-06-14 16:09:07.200	OpenQueryStore captured 0 runtime statistics...
1325	265	2017-06-14 16:09:07.200	OpenQueryStore capture script finished...

**Comment by Evdlaar** [comment]
Hi Bjoern,

We added a new script "[ServiceBrokerCertificate.sql](https://github.com/OpenQueryStore/OpenQueryStore/blob/master/ServiceBrokerCertificate.sql)" that you will need to run.
The script will create a certificate and adds it to the broker so it has sufficient permissions.

We will merge this seperate script in the main install in the future.

**Comment by sql-aus-hh** [comment]
if you change the "USE MASTER" against "USE master" it should work on all environments ;-) 
here i throws an error with capital letters


But still the same message in log and in log table

**Comment by Evdlaar** [comment]
If you query the oqs.plans table it is empty as well?

**Comment by Evdlaar** [comment]
And does it work if you run the stored procedure manually like:

EXEC oqs.Gather_Statistics @logmode = 1

**Comment by sql-aus-hh** [comment]
there are only two lines from StartScheduler and StopScheduler procedure creation.

EXEC oqs.Gather_Statistics @logmode = 1

Msg 8152, Level 16, State 10, Procedure Gather_Statistics, Line 36
String or binary data would be truncated.
The statement has been terminated.

Sorry :-(

**Comment by Evdlaar** [comment]
Did you remove the stored procedure and recreated it from the latest install script on this GitHub page?
We just tested it on every SQL version from 2008R2 and up and it works without issue.

**Comment by sql-aus-hh** [comment]
The gathering stop? yes, drop and recreate from your script. I'll try again give me a moment

**Comment by sql-aus-hh** [comment]
recreated start- stop- and gathering stop...
then dropped certificates and recreated them

still

EXEC oqs.Gather_Statistics @logmode = 1

Msg 8152, Level 16, State 10, Procedure Gather_Statistics, Line 36
String or binary data would be truncated.
The statement has been terminated.

**Comment by Evdlaar** [comment]
Very strange.
We will look into this.

Thanks for your testing so far!

**Comment by sql-aus-hh** [comment]
I'll build up my own test server and try it there (on a fresh environment)

**Comment by sql-williamd** [comment]
The latest build from last night should now resolve this issue. We also have an uninstall routine that currently removes all traces of OQS from a SQL server. Run that first.

Please also be aware we have changed object names, so the uninstaller right now will not clean up the old objects (you'll need to do that by hand this time)

**Comment by sql-williamd** [comment]
Closing this bug now. We are not seeing the issue on our test builds. Please re-open if you are still having issues
