### ISSUE TITLE
Installation on Windows 2012 R2 and SQL Server 2008R2 SP3 MS15_58

### ISSUE THREAD

**Issue by sql-aus-hh** [OpenQueryStore/OpenQueryStore#12]
Fresh installation (in Azure) for testing the other issue
I ran into following message:

Msg 6510, Level 16, State 11, Procedure Gather_Statistics, Line 37 [Batch Start Line 241]
This functionality requires .NET Framework 3.5 SP1. Please install .NET Framework 3.5 SP1 to use this functionality.

Please put this into installation documentation.

**Comment by sql-williamd** [comment]
The documentation has been updated to reflect minimum requirements
