### ISSUE TITLE
[DOCS] SQL Server (actual) Minimum Requirements

### ISSUE THREAD

**Issue by ClaudioESSilva** [OpenQueryStore/OpenQueryStore#14]
As it is today, and regarding installation, the current minimum version of SQL Server need to be:
 - Microsoft SQL Server 2008 /R2 – Service Pack 1
 - Microsoft SQL Server v2012 – RTM

This happens because we are trying to use the following columns from `sys.dm_exec_query_stats`:
- 'total_rows'
- 'last_rows'
- 'min_rows'
- 'max_rows'

![image](https://user-images.githubusercontent.com/19521315/27232426-eaa8a4e8-52ad-11e7-9cf3-8029589632db.png)

https://learningintheopen.org/tag/number-of-records-returned-for-query/

I suggest changing the readme.md to match this and also to say that backward compatibility (2005) will come soon 👍

**Comment by sql-williamd** [comment]
Hi Cláudio,

I'm actually working on fixing this right now. We were a bit quick announcing and didn't expect any interest in it until it was a bit more mature :)

We'll be implementing a versioned view to abstract away this issue. Stay tuned for the next release.

**Comment by ClaudioESSilva** [comment]
No problem William. I was curious about it decide to test it 😊
I understood that you will support from 2005 but just in case some earlier adopters jump in, I feel that info was missing. 
I will continue and provide more feedback 😉
