### ISSUE TITLE
cannot deploy report

### ISSUE THREAD

**Issue by chrgraefe** [OpenQueryStore/OpenQueryStore#17]
Hi,

Installation of sql script runs well, but the deployment of the report fails with the error message attached to the issue!

regards
Christian

![image](https://user-images.githubusercontent.com/4922897/27373596-2f41a3a2-5669-11e7-928a-51decd3e181a.png)

configuration server:
- Windows Server 2008 R2
- SQL Server 2008

configuration client:
- Windows 10 Pro
- SSMS 17.1 (german)

**Comment by Evdlaar** [comment]
Hi,

Right now there is an issue displaying the report on SSMS 17.x.
We are working on an updated version of the report that will be compatible with 17.x.

**Comment by Evdlaar** [comment]
Pull request with the changes to the report have been merged!
Thanks for your work!
