### ISSUE TITLE
UninstallClassic.sql - Cannot Drop Certificate

### ISSUE THREAD

**Issue by sql-aus-hh** [OpenQueryStore/OpenQueryStore#20]
Msg 15559, Level 16, State 1, Line 120
Cannot drop certificate 'OpenQueryStore' because there is a user mapped to it.

This happened on my machine (which might be different)...

I was able to drop my certificate after dropping database login which where created here (ServiceBrokerCertificate.sql):

-- Create the login using the certificate
CREATE LOGIN [OpenQueryStore]
FROM CERTIFICATE [OpenQueryStore];
GO

**Comment by sql-williamd** [comment]
There is a DROP LOGIN in the uninstall script. Can you run the uninstall again, one command at a time and see if your error repeats?

**Comment by sql-aus-hh** [comment]
You can close this, script runs successfully. Seems to be my own fault from trying around and finding failures or getting it to run on that machine. Sorry
