### ISSUE TITLE
Cannot install Custom Report on database

### ISSUE THREAD

**Issue by sql-aus-hh** [OpenQueryStore/OpenQueryStore#21]
![image](https://user-images.githubusercontent.com/20439825/27536279-b69a70b4-5a6e-11e7-9af1-d6e8d240885b.png)

Sorry, I'm not that confident with custom reports so I'm not able to fix it myself.
SQL Server 2008 R2 (10.50.6220)

**Comment by Evdlaar** [comment]
This appears to be a bug related to the compilation of the report.
Until we get this fixed I would recommend using SSMS v16.x or 17.x to view the report.

**Comment by Evdlaar** [comment]
Closing this one since from the latest release on we only support SSMS 16.x and 17.x.
