### ISSUE TITLE
fn_repl_hash_binary is not working in SQL 2008 if FIPS-140-2 policy is true

### ISSUE THREAD

**Issue by chrgraefe** [OpenQueryStore/OpenQueryStore#22]
Hi,

on my machine the policy described in the link was set to true.

https://support.microsoft.com/en-us/help/955720/instructions-for-using-sql-server-2008-in-fips-140-2-compliant-mode

This caused SQL Server 2008 throw an exception at the use of fn_repl_hash_binary

Turning the policy of helped for this issue

**Comment by sql-williamd** [comment]
Wow!!! FIPS compliance kicking our ass...... Don't know what we can do here, other than say "don't use FIPS"...... Any suggestions @chrgraefe ?

**Comment by chrgraefe** [comment]
Hi William, I totally agree, we can't do anything in this case, than suggesting not to activate it.
Plese close this issue. It's just for document this behavior.

Message was (in german): 
_The activated proc '[oqs].[ActivateOQSScheduler]' running on queue 'DBA.oqs.OQSScheduler' output the following:  'A .NET Framework error occurred during execution of user-defined routine or aggregate "fn_repl_hash_binary":   System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.InvalidOperationException: Diese Implementation ist nicht Teil der FIPS-validierten kryptographischen Algorithmen für die Windows-Plattform.  System.InvalidOperationException:      bei System.Security.Cryptography.MD5CryptoServiceProvider..ctor()  System.Reflection.TargetInvocationException:      bei System.RuntimeMethodHandle._InvokeConstructor(Object[] args, SignatureStruct& signature, IntPtr declaringType)     bei System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)     bei System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)     bei System.Security.Cryptography.MD5.Create()     bei CSqlReplExtended.fn_Repl_Hash_Binary(SqlBytes input)  .'_

**Comment by sql-williamd** [comment]
Thanks for the feedback. I'll add the warning to the install docs.
