### ISSUE TITLE
EXECUTE [master].[dbo].[OpenQueryStoreStartup] fails after installation

### ISSUE THREAD

**Issue by chrgraefe** [OpenQueryStore/OpenQueryStore#32]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x ] *bug*:

## Instance Details
Run the following instruction on your SQL Server instance:
```SQL 
SELECT @@VERSION 
```
and paste the output here
Microsoft SQL Server 2008 (SP4-OD) (KB3144113) - 10.0.6547.0 (X64)   Feb 22 2016 19:04:50   Copyright (c) 1988-2008 Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) 

#### Example:
As provided by the Install.ps1 script
1. EXECUTE [master].[dbo].[OpenQueryStoreStartup]

2. received following error
```SQL
Msg 2812, Level 16, State 62, Procedure OpenQueryStoreStartup, Line 8 [Batch Start Line 2]
Die gespeicherte Prozedur 'DBA.oqs.StartScheduler' wurde nicht gefunden.
(1 row affected)
```

**Comment by sql-williamd** [comment]
This was a typo in the install script post-installation instructions, it should be `dbo.open_query_store_startup`

Install.ps1 has been updated

**Comment by chrgraefe** [comment]
Thank you

**Comment by chrgraefe** [comment]
Thank you
