### ISSUE TITLE
Create Uninstall.ps1

### ISSUE THREAD

**Issue by chrgraefe** [OpenQueryStore/OpenQueryStore#33]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x ] *feature* 
- [ ] *bug*:

## Instance Details
Run the following instruction on your SQL Server instance:
```SQL 
SELECT @@VERSION 
```
and paste the output here
- no

Please provide uninstall scipt via PowerShell to be consistent

**Comment by sql-williamd** [comment]
fixed in v2.0.1 release
