### ISSUE TITLE
Broken installation in Centralized mode reports wrong things and puts me in the middle-stage

### ISSUE THREAD

**Issue by NowinskiK** [OpenQueryStore/OpenQueryStore#34]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Instance Details
Run the following instruction on your SQL Server instance:
```SQL 
SELECT @@VERSION 
```
and paste the output here
- SQL Server version and edition: Microsoft SQL Server 2014 (SP2-CU3) (KB3204388) - 12.0.5538.0 (X64) 
	Dec 15 2016 17:52:48 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

#### Example:
1. Run installation script:
.\Install.ps1 -SqlInstance "WDxxxx" -Database YYYYY -OQSMode "Centralized" -SchedulerType "Service Broker" -CertificateBackupPath "C:\temp"
2. I've got message "Installing OQS Service Broker objects" and the process did hang for a while 
3. After some time I've got error messages:
> Exception calling "ExecuteNonQuery" with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or batch."
4. Next step of installation was similar: "Installing OQS Service Broker certificate"
> Exception calling "ExecuteNonQuery" with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or batch."
5. At the end, I've received confusing information, like this:
>WARNING: OQS Service Broker installation completed successfully. Collection will start after an instance restart or by running 'EXECUTE [master].[dbo].[dbo.open_query_st
ore_startup]'.
WARNING: Centralized mode requires databases to be registered for OQS to monitor them. Please add the database names into the table oqs.monitored_databases.
WARNING: To avoid data collection causing resource issues, OQS data capture is deactivated. 
WARNING: Please update the value in column 'collection_active' in table oqs.collection_metadata as follows: UPDATE [oqs].[collection_metadata] SET [collection_active] = 1
WARNING: Please remove the file C:\temp\open_query_store.CER as it is no longer needed and will prevent a fresh install of OQS at a later time.
WARNING: Open Query Store installation complete.

Collecting process doesn't work. I'll investigate the root cause.
Now, I don't know how to evaluate the progress of installation and/or how to continue, validate or revert installation.

## Attached screen shots/SSMS output
![image](https://user-images.githubusercontent.com/25029325/29635530-3e034180-8845-11e7-842d-050c6084628e.png)

- Provide screen shots of the output from your SSMS if available.

**Comment by sql-williamd** [comment]
Thanks for the bug report.

This is an issue of activating Service Broker on a database..... the command to turn on Service Broker requires an exclusive database lock, which I assume wasn't possible here.

You will need to run uninstall to clean up, then re-install, ensuring the target database isn't being used by other uses/processes.

I will re-write the installer to catch this and update the wiki to reflect this too.

I'll close this issue when the full fix is implemented

**Comment by js0505** [comment]
I get same error when running centralized and SQL Agent

**Comment by sql-williamd** [comment]
@js0505 - can you file a separate report and include the same details please, because you are seeing it with a different set of options

**Comment by sql-williamd** [comment]
This has been fixed in the 2.0.2 release, so should not occur any more
