### ISSUE TITLE
Wrong examples of using in the Uninstall.ps1 script

### ISSUE THREAD

**Issue by NowinskiK** [OpenQueryStore/OpenQueryStore#35]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Instance Details
Doesn't matter.

#### Example:
1. Run Uninstall.ps1 script as following:
.\UnInstall.ps1 -SqlInstance "WDxxxx" -Database "YYYYY" -OQSMode "Centralized" -SchedulerType "Service Broker" -CertificateBackupPath "C:\temp"
So, when you use one of these args: OQSMode, SchedulerType or CertificateBackupPath - it will fail.

And I've tried that way because I'm a new user and because of this description:
![image](https://user-images.githubusercontent.com/25029325/29635840-3e194a88-8846-11e7-96bb-092ef379b3ec.png)

## Attached screen shots/SSMS output

- Provide screen shots of the output from your SSMS if available.
![image](https://user-images.githubusercontent.com/25029325/29635735-cff750ae-8845-11e7-8802-f464a48a5a8c.png)

**Comment by sql-williamd** [comment]
The example text has been updated and will be part of the upcoming v2.1 release
