### ISSUE TITLE
Wait Statistics report - hidden wait types

### ISSUE THREAD

**Issue by fatherjack** [OpenQueryStore/OpenQueryStore#38]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x ] *feature* 
- [ ] *bug*:

## Instance Details
Can we have a hyperlink in the report to a list of the waits that are described as 'benign' please?

**Comment by Evdlaar** [comment]
Good point!
This will be added in the openquerystore.com website soon!

**Comment by fatherjack** [comment]
Wait details created at https://github.com/OpenQueryStore/OpenQueryStore/wiki/BenignWaits. rdl only needs link to be added and this is then complete

**Comment by sql-williamd** [comment]
fixed with latest commit (should have used "close" in the commit to auto-close this issue)
