### ISSUE TITLE
Option to ignore queries from OQS

### ISSUE THREAD

**Issue by sql-williamd** [OpenQueryStore/OpenQueryStore#49]
In making demos to show how OQS works, there are a lot of system queries that SSMS makes that "muddy the waters" of OQS (especially when using intellisense).

We should have an option to remove/ignore certain queries from OQS. I don't know if we should collect them and filter out for presentation, or provide a way of ignoring them at collection time.

**Comment by ClaudioESSilva** [comment]
Do you have any idea how you will filter them? 
That can help answering.

**Comment by sql-williamd** [comment]
My first idea is to have an option to identify a collected query_id as "bad". This would go into a "bad queries" table that is used to filter out collection of these queries.

The other way would be to collect everything and have a way of marking queries that should be ignored for the dashboard (an extra 'ignore' column or something like that). So they are collected and can be seen if wanted, but by default they are "hidden"

**Comment by ClaudioESSilva** [comment]
I like the 2nd way. In this kind of stuff I prefer to have more than less and then hide/ignore the "trash".

But my primary question is how you gonna identify the "bad" query_id? Do we have anything that say that? What makes it bad? 
Do you know how Query Store (2016+) handle this? Or, the question should be, does it handle?

**Comment by fatherjack** [comment]
my 2 cents ...
Have you considered using a process ID to prevent specified queries from appearing in OQS? For demo purposes this would be easily identified and of a limited range (perhaps you have 4-6 queries open during the demo) so you could pass in a 'black list' to a config table. For SSMS queries - I think they are handled by a system SPID so < 50 would prevent those showing.

**Comment by sql-williamd** [comment]
SSMS queries are SPID < 50?! even though they are caused by the "user"?? if so, then that could be interesting for sure

**Comment by sql-williamd** [comment]
@ClaudioESSilva - the identification of "bad" queries is by the OQS-Admin themselves. In my testing for the demo I saw one query executed more than any others by a large margin. This showed on the OQS dashboard.

The problem there was, that it is a noisy but unintersting query (I can't fix SSMS intellisense), so being able to "turn it off" for OQS purposes would be important.

**Comment by fatherjack** [comment]
fair point well made!

How about filtering by ProgramName - would allow for removal of other tools too?

**Comment by ClaudioESSilva** [comment]
@sql-williamd this "the identification of "bad" queries is by the OQS-Admin themselves" is what I was looking for. If we need to add it manually do the exclusion table (if we can't find a better way), I suggest to allow different types of filters like user/login, program_name, host(?) maybe this way we can get the best of both worlds (this way we can include @fatherjack 's good suggestions too 😄 )

I'm not sure if it will over-complicate and slow-down the query responsible by collect the data. I do not think so, but it needs some testing.

**Comment by sql-williamd** [comment]
ahh, wait, scratch that. We are working from [sys].[dm_exec_cached_plans]..... there is no correlation to a user/connection/session with how OQS works......

We only have the option of filtering on the queries we capture and the data stored within.

This leaves us with query_ids that are assigned by OQS, or other sqlplan attributes......

**Comment by ClaudioESSilva** [comment]
By looking into [sys.dm_exec_plan_attributes](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-plan-attributes-transact-sql) I would say that `dbid` and `user_id` may be good candidates.  Also, maybe `dbid_execute <> 0` can help too.
But not so granular as the other idea we had 😅 

Well even 'user_id' can be tricky and make us keep tracking of it?

**Comment by ClaudioESSilva** [comment]
Oh even `dbid` can be tricky, iirc, if you run a query like SELECT columns FROM [db1].[dbo].[table] but connected to other database than 'db1', let's say 'master', the `dbid` value will be the database where it ran which means 'master'

**Comment by fatherjack** [comment]
Dont forget you can indeed turn off intellisense ...

**Comment by sql-williamd** [comment]
@fatherjack - yes, I can.... but this demonstrates that other people will probably have similar situations where certain queries can be ignore and also skew the metrics. turning them on/off in OQS would be helpful IMO
