### ISSUE TITLE
Installation fails when certificate already installed on the instance

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [OpenQueryStore/OpenQueryStore#60]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [ X] *bug*:

Installation fails when certificate already installed on the instance

**Comment by sql-williamd** [comment]
check out line 341 of setup.ps1...... there *is* a certificate check at install time. it should skip installation if a cert exists already......

**Comment by SQLDBAWithABeard** [comment]
You are correct. Wer will take the example that caused this issue as being down to external circumstances
