### ISSUE TITLE
Latest version get the following error.

### ISSUE THREAD

**Issue by nickm324** [OpenQueryStore/OpenQueryStore#65]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Instance Details
Run the following instruction on your SQL Server instance:
```SQL 
SELECT @@VERSION 
```
and paste the output here
- SQL Server version and edition: _<result of execution>_

#### Example:
1. Created table dbo.abc
2. Inserted data
3. Created stored procedure/etc
4. Run Command:
```SQL
execute dbo.someStoredProcedure
```
5. Open the report and received following error
```SQL
Cannot find object name 'oqs.someTable'
```

## Attached screen shots/SSMS output

- Provide screen shots of the output from your SSMS if available.

**Comment by nickm324** [comment]
.\Install.ps1 -SqlInstance MSSQLSERVER -Database pcs -OQSMode Classic -SchedulerType "Service Broker" -CertificateBackupPath "c:\certbackup"

The "=" operator is missing after a named argument.
At C:\Users\Administrator\Desktop\OpenQueryStore-2.1.0\OpenQueryStore-2.1.0\Install.ps1:140 char:34
+             [parameter(Mandatory, <<<<  ValueFromPipeline)]
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEqualsInNamedArgument

**Comment by nickm324** [comment]
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64)   Apr  2 2010 15:48:46   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

**Comment by ClaudioESSilva** [comment]
Hi @nickm324, which PowerShell version are your running?
Please run `$psversiontable` on the console and paste the output here.
Thanks!

**Comment by nickm324** [comment]
Name                           Value
----                           -----
CLRVersion                     2.0.50727.8669
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1

**Comment by ClaudioESSilva** [comment]
Thank you @nickm324.
The minimum PowerShell version required for OQS is v3.

Note: We will update the Wiki with that info.

**Comment by nickm324** [comment]
ok thanks. I will try and update PowerShell on this machine.

**Comment by nickm324** [comment]
Is there any logging? I got the script to run but am getting a new error that I cant see how to track down.

PS C:\Users\Administrator\Desktop\OpenQueryStore-2.1.0\OpenQueryStore-2.1.0> .\Install.ps1 -SqlInstance "DEVDB007" -Data
base "pcs" -OQSMode "Classic"-SchedulerType "Service Broker" -CertificateBackupPath "C:\Temp"
WARNING: There was an error at Failed to install base SQL query - Running Uninstall then quitting - Error details are
in $OQSError
Open Query Store has been uninstalled due to errors in installation - Please review
PS C:\Users\Administrator\Desktop\OpenQueryStore-2.1.0\OpenQueryStore-2.1.0>

**Comment by sql-williamd** [comment]
if you are still in PowerShell Console, you can run the command "$OQSError" and that should dump the error to screen.

**Comment by nickm324** [comment]
Yea I tried that first and it just returns a blank command prompt line. Like I was on the command prompt and just hit enter.

**Comment by sql-williamd** [comment]
It failed at the point of installing the base objects..... this is very early in the install process. Can you take a look in SSMS to see what, if anything, has been created so far?

**Comment by nickm324** [comment]
Yea I went through and I cannot find anything that was created.  No tables, SPs, functions, etc.

**Comment by sql-williamd** [comment]
I assume you have permissions on the server. We create a schema, some tables etc. You can see what is going on inside the .sql files like in "install_open_query_store_base.sql" in the setup folder.

**Comment by nickm324** [comment]
I ran the script manually after changing all the {} values, it appears to run for the most part but ends on trying to create a view which generates these errors. And even after that I still do not see anything defined with a "oqs" schema or anything related. Maybe I am just not looking in the correct place for whats getting created.

Msg 207, Level 16, State 1, Procedure query_stats, Line 34
Invalid column name 'total_rows'.
Msg 207, Level 16, State 1, Procedure query_stats, Line 34
Invalid column name 'last_rows'.
Msg 207, Level 16, State 1, Procedure query_stats, Line 34
Invalid column name 'min_rows'.
Msg 207, Level 16, State 1, Procedure query_stats, Line 34
Invalid column name 'max_rows'.

**Comment by nickm324** [comment]
Ok I am just stupid, I see all the tables now, had a filter on I wasn't aware of, in any case when I run the script I do still get those errors above.

**Comment by sql-williamd** [comment]
now I know the issue. we dynamically create a view to get query stats..... those columns don't exist on older versions of SQL Server. This looks to be a case where the columns were added between versions.

Can you run this please:

DECLARE @MajorVersion   tinyint,
        @MinorVersion   tinyint,
		@BuildVersion	int,
        @Version        nvarchar (128),
        @ViewDefinition nvarchar (MAX);

SELECT @Version = CAST(SERVERPROPERTY( 'ProductVersion' ) AS nvarchar);

SELECT @MajorVersion = PARSENAME( CONVERT( varchar (32), @Version ), 4 ),
       @MinorVersion = PARSENAME( CONVERT( varchar (32), @Version ), 3 ),
       @BuildVersion = PARSENAME( CONVERT( varchar (32), @Version ), 2 );

**Comment by nickm324** [comment]
Ok, I ran what you posted above. Only output was "Command(s) completed successfully."

**Comment by sql-williamd** [comment]
sorry, my mistake:

DECLARE @majorversion tinyint,
@minorversion tinyint,
@buildversion	int,
@Version nvarchar (128),
@viewdefinition nvarchar (MAX);

SELECT @Version = CAST(SERVERPROPERTY( 'ProductVersion' ) AS nvarchar);

SELECT majorversion = PARSENAME( CONVERT( varchar (32), @Version ), 4 ),
minorversion = PARSENAME( CONVERT( varchar (32), @Version ), 3 ),
buildversion = PARSENAME( CONVERT( varchar (32), @Version ), 2 );

**Comment by sql-williamd** [comment]
this will expand the version number information of your sql server. we will then need to fix the view creation code to work on your version

**Comment by nickm324** [comment]
majorversion	minorversion	buildversion
10	50	1600

**Comment by sql-williamd** [comment]
That is weird..... the version check that we do covers the version you are using.

Can you run this inside the OQS target database (it is the same portion of code from the installer, just extracted to run once manually)


DECLARE @MajorVersion   tinyint,
        @MinorVersion   tinyint,
		@BuildVersion	int,
        @Version        nvarchar (128),
        @ViewDefinition nvarchar (MAX);

SELECT @Version = CAST(SERVERPROPERTY( 'ProductVersion' ) AS nvarchar);

SELECT @MajorVersion = PARSENAME( CONVERT( varchar (32), @Version ), 4 ),
       @MinorVersion = PARSENAME( CONVERT( varchar (32), @Version ), 3 ),
       @BuildVersion = PARSENAME( CONVERT( varchar (32), @Version ), 2 );

SET @ViewDefinition = 'CREATE VIEW [oqs].[query_stats]
AS
SELECT [sql_handle],
       [statement_start_offset],
       [statement_end_offset],
       [plan_generation_num],
       [plan_handle],
       [creation_time],
       [last_execution_time],
       [execution_count],
       [total_worker_time],
       [last_worker_time],
       [min_worker_time],
       [max_worker_time],
       [total_physical_reads],
       [last_physical_reads],
       [min_physical_reads],
       [max_physical_reads],
       [total_logical_writes],
       [last_logical_writes],
       [min_logical_writes],
       [max_logical_writes],
       [total_logical_reads],
       [last_logical_reads],
       [min_logical_reads],
       [max_logical_reads],
       [total_clr_time],
       [last_clr_time],
       [min_clr_time],
       [max_clr_time],
       [total_elapsed_time],
       [last_elapsed_time],
       [min_elapsed_time],
       [max_elapsed_time],' + 
CASE WHEN @MajorVersion = 9 THEN 'CAST(NULL as binary (8)) ' ELSE '' END + '[query_hash],' +											-- query_hash appears in sql 2008
CASE WHEN @MajorVersion = 9 THEN 'CAST(NULL as binary (8)) ' ELSE '' END + '[query_plan_hash],' +										-- query_plan_hash appears in sql 2008
CASE WHEN @MajorVersion = 9 OR ( @MajorVersion = 10 AND @MinorVersion < 50 AND @BuildVersion < 2500 ) THEN 'CAST(0 as bigint) ' ELSE '' END + '[total_rows],' +	-- total_rows appears in sql 2008r2 SP1
CASE WHEN @MajorVersion = 9 OR ( @MajorVersion = 10 AND @MinorVersion < 50 AND @BuildVersion < 2500 ) THEN 'CAST(0 as bigint) ' ELSE '' END + '[last_rows],' +	-- last_rows appears in sql 2008r2 SP1
CASE WHEN @MajorVersion = 9 OR ( @MajorVersion = 10 AND @MinorVersion < 50 AND @BuildVersion < 2500 ) THEN 'CAST(0 as bigint) ' ELSE '' END + '[min_rows],' +	-- min_rows appears in sql 2008r2 SP1
CASE WHEN @MajorVersion = 9 OR ( @MajorVersion = 10 AND @MinorVersion < 50 AND @BuildVersion < 2500 ) THEN 'CAST(0 as bigint) ' ELSE '' END + '[max_rows],' +	-- max_rows appears in sql 2008r2 SP1
CASE WHEN @MajorVersion < 12 THEN 'CAST(NULL as varbinary (64)) ' ELSE '' END + '[statement_sql_handle],' +								-- statement_sql_handle appears in sql 2014
CASE WHEN @MajorVersion < 12 THEN 'CAST(NULL as bigint) ' ELSE '' END + '[statement_context_id],' +										-- statement_context_id appears in sql 2014
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[total_dop],' +													-- total_dop appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[last_dop],' +													-- last_dop appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[min_dop],' +														-- min_dop appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[max_dop],' +														-- max_dop appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[total_grant_kb],' +												-- total_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[last_grant_kb],' +												-- last_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[min_grant_kb],' +												-- min_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[max_grant_kb],' +												-- max_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[total_used_grant_kb],' +											-- total_used_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[last_used_grant_kb],' +											-- last_used_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[min_used_grant_kb],' +											-- min_rows appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[max_used_grant_kb],' +											-- max_used_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[total_ideal_grant_kb],' +										-- total_ideal_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[last_ideal_grant_kb],' +											-- last_ideal_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[min_ideal_grant_kb],' +											-- min_ideal_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[max_ideal_grant_kb],' +											-- max_ideal_grant_kb appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[total_reserved_threads],' +										-- total_reserved_threads appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[last_reserved_threads],' +										-- last_reserved_threads appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[min_reserved_threads],' +										-- min_reserved_threads appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[max_reserved_threads],' +										-- max_reserved_threads appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[total_used_threads],' +											-- total_used_threads appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[last_used_threads],' +											-- last_used_threads appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[min_used_threads],' +											-- min_used_threads appears in sql 2016
CASE WHEN @MajorVersion < 13 THEN 'CAST(0 as bigint) ' ELSE '' END + '[max_used_threads]' +												-- max_used_threads appears in sql 2016
' FROM [sys].[dm_exec_query_stats];';

EXEC ( @ViewDefinition );
GO

**Comment by nickm324** [comment]
Msg 207, Level 16, State 1, Procedure query_stats, Line 34
Invalid column name 'total_rows'.
Msg 207, Level 16, State 1, Procedure query_stats, Line 34
Invalid column name 'last_rows'.
Msg 207, Level 16, State 1, Procedure query_stats, Line 34
Invalid column name 'min_rows'.
Msg 207, Level 16, State 1, Procedure query_stats, Line 34
Invalid column name 'max_rows'.

**Comment by sql-williamd** [comment]
I've made you a special version of the base objects installer. please replace your local version with this one (careful to rename this, because it is currently a .txt file)

[install_open_query_store_base.sql.txt](https://github.com/OpenQueryStore/OpenQueryStore/files/1613164/install_open_query_store_base.sql.txt)


You can then run the uninstall.ps1 to clean up and then re-run the install and see if that works.

**Comment by nickm324** [comment]
Yep ran fine that time. Thanks for the help.
