### ISSUE TITLE
Error at installation

### ISSUE THREAD

**Issue by mvillegascuellar** [OpenQueryStore/OpenQueryStore#68]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x ] *bug*:

## Instance Details
Run the following instruction on your SQL Server instance:
```SQL 
SELECT @@VERSION 
```
and paste the output here
- SQL Server version and edition: _<result of execution>_

Microsoft SQL Server 2012 (SP4-GDR) (KB4057116) - 11.0.7462.6 (X64) 
	Jan  5 2018 22:11:56 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

## Steps to Reproduce

PS C:\tss\OpenQueryStore-2.3.0> .\Install.ps1 -SqlInstance localhost\dev -Database DB-Dev1 -OQSMode Classic -SchedulerType "Service Broker" -CertificateBackupPath "C:\tss\OQS" -Verbose
                                    

## Attached screen shots/SSMS output

![2018-03-15_10-27-38](https://user-images.githubusercontent.com/25183564/37473064-8386d140-283b-11e8-8598-e0980a66c664.png)

**Comment by mvillegascuellar** [comment]
Hi, yes indeed.

**Comment by sql-williamd** [comment]
fixed by #69
