### ISSUE TITLE
Small issue in installation documentation (wiki)

### ISSUE THREAD

**Issue by sql-aus-hh** [OpenQueryStore/OpenQueryStore#9]
Hi,

first try to install OQS and already crashed... but it was my fault because I just read the documentation without thinking...

Wiki says:
Installing OQS is a simple process.

1. Open the appropriate installer (classic or centralised) in your favourite T-SQL editor.
2. Connect to the SQL Server instance where you wish to install OQS.
3. Run the entire T-SQL code
4. You're done!

I know OQS and QS both has to be activated on database-level so installation of OQS should be performed in that database that shall be monitored.

Please add another point (just for the nonthinking people ;-) ) :
1. Open the appropriate installer (classic or centralised) in your favourite T-SQL editor.
2. Connect to the SQL Server instance where you wish to install OQS.
**_3. Choose your database which should be monitored_**
4. Run the entire T-SQL code
5. You're done!

**Comment by Evdlaar** [comment]
Thanks for the suggestion, this was an oversight on our part.
The guide now has an added step: "_Launch a new query window and make sure the correct user database in which you want to install OQS is selected._"

Thanks for taking the time to provide feedback!
